import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { z } from 'zod';

import { PreaurRawConfigSchema } from './config_schema';

type JsonSchema = Record<string, any>;

interface ConfigSection {
    title: string;
    description: string;
    rows: ConfigReferenceRow[];
    level: number;
}

interface ConfigReferenceRow {
    key: string;
    required: boolean;
    type: string;
    defaultValue: string;
    description: string;
}

const rootDir = path.resolve(import.meta.dir, '..');
const schemaPath = path.resolve(rootDir, 'preaur.schema.json');
const docsPath = path.resolve(rootDir, 'docs', 'config-reference.md');

const schema = z.toJSONSchema(PreaurRawConfigSchema, {
    target: 'draft-7',
    io: 'input',
}) as JsonSchema;

schema.$schema = 'http://json-schema.org/draft-07/schema#';

await fs.writeFile(schemaPath, `${JSON.stringify(schema, null, 4)}\n`, 'utf8');
await fs.mkdir(path.dirname(docsPath), { recursive: true });
await fs.writeFile(docsPath, renderConfigReference(schema), 'utf8');

console.log(`Generated ${path.relative(rootDir, schemaPath)}`);
console.log(`Generated ${path.relative(rootDir, docsPath)}`);

function renderConfigReference(schema: JsonSchema): string {
    const sections = collectSections(schema);
    const lines = [
        '# Config Reference',
        '',
        '<!-- This file is generated by `bun run gen-schema`. Do not edit by hand. -->',
        '',
    ];

    for (const section of sections) {
        lines.push(`${'#'.repeat(section.level)} ${section.title}`, '');
        if (section.description) {
            lines.push(section.description, '');
        }
        lines.push(...renderSectionTable(section.rows), '');
    }

    return `${lines.join('\n').trimEnd()}\n`;
}

function collectSections(root: JsonSchema): ConfigSection[] {
    const sections: ConfigSection[] = [];
    collectObjectSection(root, 'Top-Level', 2, sections);
    return sections;
}

function collectObjectSection(
    schema: JsonSchema,
    title: string,
    level: number,
    sections: ConfigSection[]
): void {
    const properties = schema.properties ?? {};
    const requiredKeys = new Set<string>(schema.required ?? []);

    sections.push({
        title,
        level,
        description: title === 'Top-Level' ? '' : schema.description ?? '',
        rows: Object.entries(properties).map(([key, child]) => ({
            key,
            required: requiredKeys.has(key),
            type: summarizeType(child as JsonSchema),
            defaultValue: formatDefault((child as JsonSchema).default),
            description: (child as JsonSchema).description ?? '',
        })),
    });

    for (const [key, child] of Object.entries(properties)) {
        collectChildSections(child as JsonSchema, childSectionTitle(title, key), level + 1, sections);
    }
}

function collectChildSections(
    schema: JsonSchema,
    pathName: string,
    level: number,
    sections: ConfigSection[]
): void {
    if (schema.type === 'object' && schema.properties) {
        collectObjectSection(schema, pathName, level, sections);
        return;
    }

    if (schema.type === 'array') {
        const item = arrayItemSchema(schema);
        if (!item || typeof item === 'boolean') return;

        const itemPath = `${pathName}[]`;
        if (item.type === 'object' && item.properties) {
            collectObjectSection(item, itemPath, level, sections);
            return;
        }
        collectUnionVariantSections(item, itemPath, level, sections);
        return;
    }

    collectUnionVariantSections(schema, pathName, level, sections);
}

function collectUnionVariantSections(
    schema: JsonSchema,
    pathName: string,
    level: number,
    sections: ConfigSection[]
): void {
    const variants = [...(schema.anyOf ?? []), ...(schema.oneOf ?? [])]
        .filter((variant: JsonSchema) => variant?.type === 'object' && variant.properties);

    if (variants.length === 0) return;

    for (const variant of variants) {
        const title = variantTitle(pathName, variant);
        collectObjectSection(variant, title, level, sections);
    }
}

function renderSectionTable(rows: ConfigReferenceRow[]): string[] {
    if (rows.length === 0) return ['No fields.'];

    return [
        '| Key | Required | Type | Default | Description |',
        '| --- | --- | --- | --- | --- |',
        ...rows.map(row => `| \`${row.key}\` | ${row.required ? 'yes' : 'no'} | ${escapeCell(row.type)} | ${escapeCell(row.defaultValue)} | ${escapeCell(row.description)} |`),
    ];
}

function variantTitle(pathName: string, schema: JsonSchema): string {
    const typeConst = schema.properties?.type?.const;
    if (typeof typeConst === 'string') return `${pathName}: ${typeConst}`;
    return `${pathName}: variant`;
}

function childSectionTitle(parentTitle: string, key: string): string {
    return parentTitle === 'Top-Level' ? key : `${parentTitle}.${key}`;
}

function arrayItemSchema(schema: JsonSchema): JsonSchema | boolean | undefined {
    return Array.isArray(schema.items) ? schema.items[0] : schema.items;
}

function summarizeType(schema: JsonSchema): string {
    if (Array.isArray(schema.enum)) return schema.enum.map(String).join(' | ');
    if (schema.const !== undefined) return JSON.stringify(schema.const);
    if (Array.isArray(schema.type)) return schema.type.join(' | ');
    if (schema.type === 'array') return `array<${summarizeType(arrayItemSchema(schema) as JsonSchema ?? {})}>`;
    if (schema.anyOf) return uniqueTypes(schema.anyOf).join(' | ');
    if (schema.oneOf) return uniqueTypes(schema.oneOf).join(' | ');
    if (schema.type) return schema.type;
    return 'unknown';
}

function uniqueTypes(items: JsonSchema[]): string[] {
    return [...new Set(items.map(item => summarizeType(item)))];
}

function formatDefault(value: unknown): string {
    if (value === undefined) return '';
    return JSON.stringify(value);
}

function escapeCell(value: string): string {
    return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}
