import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { z } from 'zod';

import { PreaurRawConfigSchema } from './config_schema';

type JsonSchema = Record<string, any>;

interface ConfigSection {
    title: string;
    description: string;
    rows: ConfigReferenceRow[];
    level: number;
}

interface ConfigReferenceRow {
    key: string;
    required: boolean;
    type: string;
    defaultValue: string;
    description: string;
}

const rootDir = path.resolve(import.meta.dir, '..');
const schemaPath = path.resolve(rootDir, 'preaur.schema.json');
const docsPath = path.resolve(rootDir, 'docs', 'config-reference.md');
const manDir = path.resolve(rootDir, 'docs', 'man');
const cliManPath = path.resolve(manDir, 'preaur.1');
const configManPath = path.resolve(manDir, 'preaur-config.5');
const packageInfo = JSON.parse(await fs.readFile(path.resolve(rootDir, 'package.json'), 'utf8')) as { version?: string };
const version = packageInfo.version ?? 'unknown';

const schema = z.toJSONSchema(PreaurRawConfigSchema, {
    target: 'draft-7',
    io: 'input',
}) as JsonSchema;

schema.$schema = 'http://json-schema.org/draft-07/schema#';

await fs.writeFile(schemaPath, `${JSON.stringify(schema, null, 4)}\n`, 'utf8');
await fs.mkdir(path.dirname(docsPath), { recursive: true });
await fs.writeFile(docsPath, renderConfigReference(schema), 'utf8');
await fs.mkdir(manDir, { recursive: true });
await fs.writeFile(cliManPath, renderCliManPage(version), 'utf8');
await fs.writeFile(configManPath, renderConfigManPage(schema, version), 'utf8');

console.log(`Generated ${path.relative(rootDir, schemaPath)}`);
console.log(`Generated ${path.relative(rootDir, docsPath)}`);
console.log(`Generated ${path.relative(rootDir, cliManPath)}`);
console.log(`Generated ${path.relative(rootDir, configManPath)}`);

function renderConfigReference(schema: JsonSchema): string {
    const sections = collectSections(schema);
    const lines = [
        '# Config Reference',
        '',
        '<!-- This file is generated by `bun run gen-schema`. Do not edit by hand. -->',
        '',
    ];

    for (const section of sections) {
        lines.push(`${'#'.repeat(section.level)} ${section.title}`, '');
        if (section.description) {
            lines.push(section.description, '');
        }
        lines.push(...renderSectionTable(section.rows), '');
    }

    return `${lines.join('\n').trimEnd()}\n`;
}

function renderCliManPage(version: string): string {
    return roff([
        `.TH PREAUR 1 "" "PreAUR ${roffInline(version)}" "User Commands"`,
        '.SH NAME',
        'preaur \\- automated Arch Linux package builder helper',
        '.SH SYNOPSIS',
        '.B preaur',
        '[\\fB-c\\fR \\fIpath\\fR] [\\fB-p\\fR \\fIname\\fR]',
        '.SH DESCRIPTION',
        'PreAUR checks configured packages, updates PKGBUILD metadata, builds packages, and updates a local pacman repository.',
        '.SH OPTIONS',
        '.TP',
        '.BR \\-c ", " \\-\\-config " " \\fIpath\\fR',
        'Path to the YAML configuration file. Defaults to \\fBpreaur.config.yaml\\fR.',
        '.TP',
        '.BR \\-p ", " \\-\\-pkg " " \\fIname\\fR',
        'Only process the package with this configured package name.',
        '.TP',
        '.BR \\-V ", " \\-\\-version',
        'Print the PreAUR version.',
        '.TP',
        '.BR \\-h ", " \\-\\-help',
        'Print command help.',
        '.SH FILES',
        '.TP',
        '.B preaur.config.yaml',
        'Main configuration file. See \\fBpreaur-config\\fR(5).',
        '.TP',
        '.B data/versions.json',
        'Stored package version and ownership state.',
        '.TP',
        '.B data/known_packages',
        'Known package trust list.',
        '.TP',
        '.B data/known_maintainers',
        'Known AUR maintainer trust list.',
        '.SH SEE ALSO',
        '.BR preaur-config (5),',
        '.BR makepkg (8),',
        '.BR repo-add (8)',
    ]);
}

function renderConfigManPage(schema: JsonSchema, version: string): string {
    const sections = collectSections(schema);
    const lines = [
        `.TH PREAUR-CONFIG 5 "" "PreAUR ${roffInline(version)}" "File Formats"`,
        '.SH NAME',
        'preaur.config.yaml \\- PreAUR configuration file',
        '.SH DESCRIPTION',
        'The PreAUR configuration file is YAML. It defines maintainers, package checks, build resources, project git automation, and optional chroot pacman repository settings.',
        '.SH FIELDS',
    ];

    for (const section of sections) {
        lines.push('.SS', roffInline(section.title));
        if (section.description) lines.push(roffText(section.description));

        for (const row of section.rows) {
            lines.push('.TP');
            lines.push(`.B ${roffInline(row.key)}`);
            lines.push(roffText(formatManRow(row)));
        }
    }

    lines.push(
        '.SH GENERATED FROM',
        'This page is generated from the Zod configuration schema by \\fBbun run gen-schema\\fR.',
        '.SH SEE ALSO',
        '.BR preaur (1)'
    );

    return roff(lines);
}

function collectSections(root: JsonSchema): ConfigSection[] {
    const sections: ConfigSection[] = [];
    collectObjectSection(root, 'Top-Level', 2, sections);
    return sections;
}

function collectObjectSection(
    schema: JsonSchema,
    title: string,
    level: number,
    sections: ConfigSection[]
): void {
    const properties = schema.properties ?? {};
    const requiredKeys = new Set<string>(schema.required ?? []);

    sections.push({
        title,
        level,
        description: title === 'Top-Level' ? '' : schema.description ?? '',
        rows: Object.entries(properties).map(([key, child]) => ({
            key,
            required: requiredKeys.has(key),
            type: summarizeType(child as JsonSchema),
            defaultValue: formatDefault((child as JsonSchema).default),
            description: (child as JsonSchema).description ?? '',
        })),
    });

    for (const [key, child] of Object.entries(properties)) {
        collectChildSections(child as JsonSchema, childSectionTitle(title, key), level + 1, sections);
    }
}

function collectChildSections(
    schema: JsonSchema,
    pathName: string,
    level: number,
    sections: ConfigSection[]
): void {
    if (schema.type === 'object' && schema.properties) {
        collectObjectSection(schema, pathName, level, sections);
        return;
    }

    if (schema.type === 'array') {
        const item = arrayItemSchema(schema);
        if (!item || typeof item === 'boolean') return;

        const itemPath = `${pathName}[]`;
        if (item.type === 'object' && item.properties) {
            collectObjectSection(item, itemPath, level, sections);
            return;
        }
        collectUnionVariantSections(item, itemPath, level, sections);
        return;
    }

    collectUnionVariantSections(schema, pathName, level, sections);
}

function collectUnionVariantSections(
    schema: JsonSchema,
    pathName: string,
    level: number,
    sections: ConfigSection[]
): void {
    const variants = [...(schema.anyOf ?? []), ...(schema.oneOf ?? [])]
        .filter((variant: JsonSchema) => variant?.type === 'object' && variant.properties);

    if (variants.length === 0) return;

    for (const variant of variants) {
        const title = variantTitle(pathName, variant);
        collectObjectSection(variant, title, level, sections);
    }
}

function renderSectionTable(rows: ConfigReferenceRow[]): string[] {
    if (rows.length === 0) return ['No fields.'];

    return [
        '| Key | Required | Type | Default | Description |',
        '| --- | --- | --- | --- | --- |',
        ...rows.map(row => `| \`${row.key}\` | ${row.required ? 'yes' : 'no'} | ${escapeCell(row.type)} | ${escapeCell(row.defaultValue)} | ${escapeCell(row.description)} |`),
    ];
}

function variantTitle(pathName: string, schema: JsonSchema): string {
    const typeConst = schema.properties?.type?.const;
    if (typeof typeConst === 'string') return `${pathName}: ${typeConst}`;
    return `${pathName}: variant`;
}

function childSectionTitle(parentTitle: string, key: string): string {
    return parentTitle === 'Top-Level' ? key : `${parentTitle}.${key}`;
}

function arrayItemSchema(schema: JsonSchema): JsonSchema | boolean | undefined {
    return Array.isArray(schema.items) ? schema.items[0] : schema.items;
}

function summarizeType(schema: JsonSchema): string {
    if (Array.isArray(schema.enum)) return schema.enum.map(String).join(' | ');
    if (schema.const !== undefined) return JSON.stringify(schema.const);
    if (Array.isArray(schema.type)) return schema.type.join(' | ');
    if (schema.type === 'array') return `array<${summarizeType(arrayItemSchema(schema) as JsonSchema ?? {})}>`;
    if (schema.anyOf) return uniqueTypes(schema.anyOf).join(' | ');
    if (schema.oneOf) return uniqueTypes(schema.oneOf).join(' | ');
    if (schema.type) return schema.type;
    return 'unknown';
}

function uniqueTypes(items: JsonSchema[]): string[] {
    return [...new Set(items.map(item => summarizeType(item)))];
}

function formatDefault(value: unknown): string {
    if (value === undefined) return '';
    return JSON.stringify(value);
}

function escapeCell(value: string): string {
    return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}

function formatManRow(row: ConfigReferenceRow): string {
    const parts = [
        `Type: ${row.type}.`,
        `Required: ${row.required ? 'yes' : 'no'}.`,
    ];
    if (row.defaultValue) parts.push(`Default: ${row.defaultValue}.`);
    if (row.description) parts.push(row.description);
    return parts.join(' ');
}

function roff(lines: string[]): string {
    return `${lines.join('\n').trimEnd()}\n`;
}

function roffText(value: string): string {
    const escaped = roffInline(value);
    return escaped.startsWith('.') || escaped.startsWith("'") ? `\\&${escaped}` : escaped;
}

function roffInline(value: string): string {
    return value
        .replaceAll('\\', '\\\\')
        .replaceAll('-', '\\-');
}
