import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { z } from 'zod';

import { PreaurRawConfigSchema } from './config_schema';

type JsonSchema = Record<string, any>;

const rootDir = path.resolve(import.meta.dir, '..');
const schemaPath = path.resolve(rootDir, 'preaur.schema.json');
const docsPath = path.resolve(rootDir, 'docs', 'config-reference.md');

const schema = z.toJSONSchema(PreaurRawConfigSchema, {
    target: 'draft-7',
    io: 'input',
}) as JsonSchema;

schema.$schema = 'http://json-schema.org/draft-07/schema#';

await fs.writeFile(schemaPath, `${JSON.stringify(schema, null, 4)}\n`, 'utf8');
await fs.mkdir(path.dirname(docsPath), { recursive: true });
await fs.writeFile(docsPath, renderConfigReference(schema), 'utf8');

console.log(`Generated ${path.relative(rootDir, schemaPath)}`);
console.log(`Generated ${path.relative(rootDir, docsPath)}`);

function renderConfigReference(schema: JsonSchema): string {
    const rows = collectRows(schema);
    const lines = [
        '# Config Reference',
        '',
        '<!-- This file is generated by `bun run gen-schema`. Do not edit by hand. -->',
        '',
        '| Path | Required | Type | Default | Description |',
        '| --- | --- | --- | --- | --- |',
        ...rows.map(row => `| \`${row.path}\` | ${row.required ? 'yes' : 'no'} | ${escapeCell(row.type)} | ${escapeCell(row.defaultValue)} | ${escapeCell(row.description)} |`),
        '',
    ];

    return lines.join('\n');
}

interface ConfigReferenceRow {
    path: string;
    required: boolean;
    type: string;
    defaultValue: string;
    description: string;
}

function collectRows(schema: JsonSchema): ConfigReferenceRow[] {
    const rows: ConfigReferenceRow[] = [];
    const seen = new Set<string>();
    visitSchema(schema, '', true, rows, seen);
    return rows;
}

function visitSchema(
    schema: JsonSchema | boolean | undefined,
    currentPath: string,
    required: boolean,
    rows: ConfigReferenceRow[],
    seen: Set<string>,
    emitSelf = true
): void {
    if (!schema || typeof schema === 'boolean') return;

    if (currentPath && emitSelf) {
        const rowKey = [
            currentPath,
            summarizeType(schema),
            formatDefault(schema.default),
            schema.description ?? '',
        ].join('\0');
        if (!seen.has(rowKey)) {
            seen.add(rowKey);
            rows.push({
                path: currentPath,
                required,
                type: summarizeType(schema),
                defaultValue: formatDefault(schema.default),
                description: schema.description ?? '',
            });
        }
    }

    if (schema.properties) {
        const requiredKeys = new Set<string>(schema.required ?? []);
        for (const [key, child] of Object.entries(schema.properties)) {
            visitSchema(
                child as JsonSchema,
                appendPath(currentPath, key),
                requiredKeys.has(key),
                rows,
                seen
            );
        }
    }

    const items = Array.isArray(schema.items) ? schema.items[0] : schema.items;
    if (items && typeof items === 'object') {
        visitSchema(items as JsonSchema, `${currentPath}[]`, true, rows, seen);
    }

    for (const variant of [...(schema.anyOf ?? []), ...(schema.oneOf ?? [])]) {
        const variantSchema = variant as JsonSchema;
        if (!variantSchema.properties && !variantSchema.items) continue;
        visitSchema(variantSchema, currentPath, required, rows, seen, false);
    }
}

function appendPath(base: string, key: string): string {
    return base ? `${base}.${key}` : key;
}

function summarizeType(schema: JsonSchema): string {
    if (Array.isArray(schema.enum)) return schema.enum.map(String).join(' | ');
    if (schema.const !== undefined) return JSON.stringify(schema.const);
    if (Array.isArray(schema.type)) return schema.type.join(' | ');
    if (schema.type === 'array') return `array<${summarizeType(schema.items ?? {})}>`;
    if (schema.anyOf) return uniqueTypes(schema.anyOf).join(' | ');
    if (schema.oneOf) return uniqueTypes(schema.oneOf).join(' | ');
    if (schema.type) return schema.type;
    return 'unknown';
}

function uniqueTypes(items: JsonSchema[]): string[] {
    return [...new Set(items.map(item => summarizeType(item)))];
}

function formatDefault(value: unknown): string {
    if (value === undefined) return '';
    return JSON.stringify(value);
}

function escapeCell(value: string): string {
    return value.replaceAll('|', '\\|').replaceAll('\n', ' ');
}
