import * as fs from 'node:fs/promises';
import * as path from 'node:path';

export interface PackageWorkDirs {
    root: string;
    srcdest: string;
    logdest: string;
    builddir: string;
    pkgdest: string;
    makepkgConf: string;
}

export interface MakepkgConfigValues {
    srcdest: string;
    logdest: string;
    builddir: string;
    pkgdest: string;
    makeflags?: string;
    compressZstdThreads?: number;
    packager?: string;
}

function safePathSegment(value: string): string {
    return value.replace(/[\/\\]/g, '_');
}

export function getPackageWorkDirs(baseDir: string, pkgname: string, logdest?: string): PackageWorkDirs {
    const root = path.resolve(baseDir, 'work', safePathSegment(pkgname));

    return {
        root,
        srcdest: path.resolve(root, 'srcdest'),
        logdest: logdest ? path.resolve(logdest) : path.resolve(root, 'logdest'),
        builddir: path.resolve(root, 'builddir'),
        pkgdest: path.resolve(root, 'pkgdest'),
        makepkgConf: path.resolve(root, 'makepkg.conf'),
    };
}

export async function ensurePackageCheckWorkDirs(workDirs: PackageWorkDirs): Promise<void> {
    await fs.mkdir(workDirs.srcdest, { recursive: true });
    await fs.mkdir(workDirs.builddir, { recursive: true });
    await fs.mkdir(workDirs.pkgdest, { recursive: true });
}

export async function ensurePackageLogDir(workDirs: PackageWorkDirs): Promise<void> {
    await fs.mkdir(workDirs.logdest, { recursive: true });
}

export function packageWorkEnv(workDirs: PackageWorkDirs): Record<string, string> {
    return {
        SRCDEST: workDirs.srcdest,
        LOGDEST: workDirs.logdest,
        BUILDDIR: workDirs.builddir,
        PKGDEST: workDirs.pkgdest,
        MAKEPKG_CONF: workDirs.makepkgConf,
    };
}

function shellQuote(value: string): string {
    return `'${value.replace(/'/g, `'\\''`)}'`;
}

export async function writeMakepkgConfig(filePath: string, values: MakepkgConfigValues): Promise<void> {
    const lines = [
        '# Generated by PreAUR. Do not edit manually.',
        'if [[ -r /etc/makepkg.conf ]]; then',
        '  source /etc/makepkg.conf',
        'fi',
        `SRCDEST=${shellQuote(values.srcdest)}`,
        `LOGDEST=${shellQuote(values.logdest)}`,
        `BUILDDIR=${shellQuote(values.builddir)}`,
        `PKGDEST=${shellQuote(values.pkgdest)}`,
    ];

    if (values.makeflags) {
        lines.push(`MAKEFLAGS=${shellQuote(values.makeflags)}`);
    }
    if (values.compressZstdThreads !== undefined) {
        lines.push(`COMPRESSZST=(zstd -c -T${values.compressZstdThreads} -)`);
    }
    if (values.packager) {
        lines.push(`PACKAGER=${shellQuote(values.packager)}`);
    }

    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, `${lines.join('\n')}\n`, 'utf8');
}

export async function writePackageMakepkgConfig(
    workDirs: PackageWorkDirs,
    overrides: Omit<Partial<MakepkgConfigValues>, 'srcdest' | 'logdest' | 'builddir' | 'pkgdest'> = {}
): Promise<void> {
    await writeMakepkgConfig(workDirs.makepkgConf, {
        srcdest: workDirs.srcdest,
        logdest: workDirs.logdest,
        builddir: workDirs.builddir,
        pkgdest: workDirs.pkgdest,
        ...overrides,
    });
}
